# Generated by Django 5.0.1 on 2025-05-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_save_interval',
            field=models.IntegerField(default=5, help_text='Auto-save interval in minutes (0 to disable)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_view',
            field=models.CharField(choices=[('list', 'List View'), ('grid', 'Grid View')], default='list', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='enable_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='items_per_page',
            field=models.IntegerField(choices=[(5, '5 items'), (10, '10 items'), (20, '20 items'), (50, '50 items')], default=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_preference',
            field=models.CharField(choices=[('all', 'All Activities'), ('important', 'Important Only'), ('none', 'No Notifications')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_recent_first',
            field=models.BooleanField(default=True, help_text='Show most recent logs first'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('light', 'Light Theme'), ('dark', 'Dark Theme'), ('green', 'Green Theme')], default='light', max_length=10),
        ),
    ]
